services:
  cargo-mq:
    container_name: "cargo-mq"
    image: rabbitmq:3.11.7-management
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "sql-server"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - sql_data:/var/opt/mssql

  cargo-api:
    build: .
    container_name: "cargo-api"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - cargo-mq
      - sql-server

volumes:
  sql_data:
    driver: local
  rabbitmq_data:
    driver: local
