name: Node.js CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Ceckout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Check and fix lint
        run: npm run lint -- --max-warnings 0 || npm run lint:fix

      - name: Check formatting
        run: npm run format

      - name: Test
        run: npm run test --if-present
